/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Areas */
        get: operations["get_areas_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{geo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Area */
        get: operations["get_area_areas__geo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layers */
        get: operations["get_layers_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Segment */
        post: operations["segment_segment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Mode
             * @enum {string}
             */
            mode: "facts" | "retrieval" | "insufficient_evidence" | "llm";
            /** Summary */
            summary: string;
            /** Limitations */
            limitations: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** Area */
        Area: {
            /** Geo Id */
            geo_id: string;
            /** Name */
            name: string;
            /**
             * Geography Type
             * @enum {string}
             */
            geography_type: "census_designated_place" | "census_tract" | "block_group";
            /** Boundary Vintage */
            boundary_vintage: string;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** Areas */
        Areas: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Features */
            features: components["schemas"]["Feature"][];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Geo Id */
            geo_id: string;
        };
        /** DataPoint */
        DataPoint: {
            /** Geo Id */
            geo_id: string;
            /** X Value */
            x_value: number | null;
            /** Y Value */
            y_value: number | null;
        };
        /** Evidence */
        Evidence: {
            /** Evidence Id */
            evidence_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "structured_data" | "document";
            /** Title */
            title: string;
            /** Source */
            source: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Date */
            date: string;
            /** Geo Id */
            geo_id: string;
            /** Metric */
            metric?: string | null;
            /** Value */
            value?: number | null;
            /** Unit */
            unit?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Page */
            page?: number | null;
            /** Section */
            section?: string | null;
        };
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: string;
            geometry: components["schemas"]["Geometry"];
            properties: components["schemas"]["Area"];
        };
        /** Geometry */
        Geometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "Polygon" | "MultiPolygon";
            /** Coordinates */
            coordinates: unknown[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Layer */
        Layer: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Description */
            description: string;
        };
        /** SegmentRequest */
        SegmentRequest: {
            /** Geo Ids */
            geo_ids: string[];
            /** X Metric */
            x_metric: string;
            /** Y Metric */
            y_metric: string;
        };
        /** SegmentResponse */
        SegmentResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** X Metric */
            x_metric: string;
            /** Y Metric */
            y_metric: string;
            /** Correlation Coefficient */
            correlation_coefficient: number | null;
            /** Sample Size */
            sample_size: number;
            /** Explanation */
            explanation: string;
            /** Data Points */
            data_points: components["schemas"]["DataPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_areas_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Areas"];
                };
            };
        };
    };
    get_area_areas__geo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                geo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Area"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layers_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"][];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_segment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
