/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Areas */
        get: operations["get_areas_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{geo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Area */
        get: operations["get_area_areas__geo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefronts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Storefronts */
        get: operations["get_storefronts_storefronts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{geo_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Area History */
        get: operations["get_area_history_areas__geo_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{geo_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Area Changes */
        get: operations["get_area_changes_areas__geo_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{geo_id}/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Area Businesses */
        get: operations["get_area_businesses_areas__geo_id__businesses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pois */
        get: operations["get_pois_pois_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Compare */
        get: operations["get_compare_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Places */
        get: operations["get_places_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overlays */
        get: operations["get_overlays_overlays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transit */
        get: operations["get_transit_transit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Community Catalog */
        get: operations["get_community_catalog_community_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layers */
        get: operations["get_layers_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Segment */
        post: operations["segment_segment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Mode
             * @enum {string}
             */
            mode: "facts" | "retrieval" | "insufficient_evidence" | "llm";
            /** Summary */
            summary: string;
            /** Limitations */
            limitations: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Claims */
            claims?: components["schemas"]["Claim"][];
        };
        /** Area */
        Area: {
            /** Geo Id */
            geo_id: string;
            /** Name */
            name: string;
            /**
             * Geography Type
             * @enum {string}
             */
            geography_type: "census_designated_place" | "census_tract" | "block_group";
            /** Boundary Vintage */
            boundary_vintage: string;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** Areas */
        Areas: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Features */
            features: components["schemas"]["Feature"][];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Geo Id */
            geo_id: string;
        };
        /** BusinessPoi */
        BusinessPoi: {
            /** Osm Id */
            osm_id: string;
            /** Name */
            name?: string | null;
            /** Category */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Geo Id */
            geo_id?: string | null;
        };
        /** BusinessResponse */
        BusinessResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Geo Id */
            geo_id?: string | null;
            /** Name */
            name?: string | null;
            /** Total */
            total: number;
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** Features */
            features: components["schemas"]["BusinessPoi"][];
            /** Attribution */
            attribution: string;
            /** License */
            license: string;
            /** Copyright Url */
            copyright_url: string;
            /** Source Date */
            source_date?: string | null;
            /** Limitations */
            limitations: string[];
        };
        /** ChangeResponse */
        ChangeResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Geo Id */
            geo_id: string;
            /** Name */
            name: string;
            /** Geography Type */
            geography_type: string;
            /** Metric */
            metric: string;
            /** Span */
            span: number;
            /** From Year */
            from_year: number;
            /** To Year */
            to_year: number;
            /** From Estimate */
            from_estimate: number | null;
            /** To Estimate */
            to_estimate: number | null;
            /** Absolute Change */
            absolute_change: number | null;
            /** Percent Change */
            percent_change: number | null;
            /**
             * Inflation Adjusted
             * @default false
             */
            inflation_adjusted: boolean;
            /** Significant 90 */
            significant_90?: boolean | null;
            /** Limitations */
            limitations: string[];
        };
        /** Claim */
        Claim: {
            /** Text */
            text: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** CommunityCatalog */
        CommunityCatalog: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Metrics */
            metrics: string[];
            /** Years */
            years: number[];
            /** Geographies */
            geographies: components["schemas"]["CommunityGeography"][];
            /** Businesses */
            businesses: number;
        };
        /** CommunityGeography */
        CommunityGeography: {
            /** Geo Id */
            geo_id: string;
            /** Name */
            name: string;
            /** Geography Type */
            geography_type: string;
            /** Zcta */
            zcta?: string | null;
        };
        /** CompareArea */
        CompareArea: {
            /** Geo Id */
            geo_id: string;
            /** Name */
            name: string;
            /** Geography Type */
            geography_type: string;
            /** Zcta */
            zcta?: string | null;
            /** Values */
            values: {
                [key: string]: components["schemas"]["CompareValue"] | null;
            };
        };
        /** CompareResponse */
        CompareResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Year */
            year: number;
            /** Metrics */
            metrics: string[];
            /** Areas */
            areas: components["schemas"]["CompareArea"][];
            /** Limitations */
            limitations: string[];
        };
        /** CompareValue */
        CompareValue: {
            /** Estimate */
            estimate: number | null;
            /** Moe */
            moe: number | null;
            /** Unit */
            unit: string;
            /**
             * Low Reliability
             * @default false
             */
            low_reliability: boolean;
            /** Span */
            span: number;
        };
        /** DataPoint */
        DataPoint: {
            /** Geo Id */
            geo_id: string;
            /** X Value */
            x_value: number | null;
            /** Y Value */
            y_value: number | null;
        };
        /**
         * DocumentScope
         * @description Reviewed contextual applicability; never a replacement for source geography.
         */
        DocumentScope: {
            /** Name */
            name: string;
            /** Context Geo Ids */
            context_geo_ids: string[];
            /**
             * Relationship
             * @enum {string}
             */
            relationship: "partial_overlap" | "broader_context";
            /** Note */
            note: string;
        };
        /** Evidence */
        Evidence: {
            /** Evidence Id */
            evidence_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "structured_data" | "document";
            /** Title */
            title: string;
            /** Source */
            source: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Date */
            date: string;
            /** Retrieved At */
            retrieved_at?: string | null;
            /** Geo Id */
            geo_id: string;
            /** Metric */
            metric?: string | null;
            /** Value */
            value?: number | null;
            /** Unit */
            unit?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Page */
            page?: number | null;
            /** Section */
            section?: string | null;
            /** Page Label */
            page_label?: string | null;
            document_scope?: components["schemas"]["DocumentScope"] | null;
        };
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: string;
            geometry: components["schemas"]["Geometry"];
            properties: components["schemas"]["Area"];
        };
        /** Geometry */
        Geometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "Polygon" | "MultiPolygon";
            /** Coordinates */
            coordinates: unknown[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Year */
            year: number;
            /** Period */
            period: string;
            /** Estimate */
            estimate: number | null;
            /** Moe */
            moe: number | null;
            /** Estimate 2024 Usd */
            estimate_2024_usd?: number | null;
            /** Moe 2024 Usd */
            moe_2024_usd?: number | null;
            /** Unit */
            unit: string;
            /**
             * Low Reliability
             * @default false
             */
            low_reliability: boolean;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Geo Id */
            geo_id: string;
            /** Name */
            name: string;
            /** Geography Type */
            geography_type: string;
            /** Zcta */
            zcta?: string | null;
            /** Metric */
            metric: string;
            /** Span */
            span: number;
            source?: components["schemas"]["HistorySource"] | null;
            /** Series */
            series: components["schemas"]["HistoryPoint"][];
            /** Limitations */
            limitations: string[];
        };
        /** HistorySource */
        HistorySource: {
            /** Dataset */
            dataset: string;
            /** Url */
            url?: string | null;
            /** Attribution */
            attribution?: string | null;
            /** License */
            license?: string | null;
        };
        /** Layer */
        Layer: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Description */
            description: string;
        };
        /** MapLineGeometry */
        MapLineGeometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "LineString" | "MultiLineString";
            /** Coordinates */
            coordinates: unknown[];
        };
        /** OverlayFeature */
        OverlayFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: string;
            geometry: components["schemas"]["Geometry"];
            properties: components["schemas"]["OverlayProperties"];
        };
        /** OverlayProperties */
        OverlayProperties: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Legal Definition */
            legal_definition?: string | null;
            /**
             * Carries Statistics
             * @default false
             */
            carries_statistics: boolean;
        };
        /** OverlayResponse */
        OverlayResponse: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Attribution */
            attribution: string;
            /** License */
            license: string;
            /** Source Url */
            source_url: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Limitations */
            limitations: string[];
            /** Features */
            features: components["schemas"]["OverlayFeature"][];
        };
        /** SegmentRequest */
        SegmentRequest: {
            /** Geo Ids */
            geo_ids: string[];
            /** X Metric */
            x_metric: string;
            /** Y Metric */
            y_metric: string;
        };
        /** SegmentResponse */
        SegmentResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** X Metric */
            x_metric: string;
            /** Y Metric */
            y_metric: string;
            /** Correlation Coefficient */
            correlation_coefficient: number | null;
            /** Sample Size */
            sample_size: number;
            /** Explanation */
            explanation: string;
            /** Data Points */
            data_points: components["schemas"]["DataPoint"][];
        };
        /** Storefront */
        Storefront: {
            /** Osm Id */
            osm_id: string;
            /** Name */
            name: string;
            /**
             * Category Key
             * @enum {string}
             */
            category_key: "shop" | "amenity";
            /** Category */
            category: string;
            /** Address */
            address: string | null;
            /** Block Group Id */
            block_group_id: string | null;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
        };
        /**
         * Storefronts
         * @description OpenStreetMap-mapped businesses. Volunteer-mapped: not a business registry.
         */
        Storefronts: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source */
            source: string;
            /** License */
            license: string;
            /** Attribution */
            attribution: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Osm Data Timestamp */
            osm_data_timestamp: string | null;
            /** Limitations */
            limitations: string;
            /** Storefronts */
            storefronts: components["schemas"]["Storefront"][];
        };
        /** TransitFeature */
        TransitFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: string;
            geometry: components["schemas"]["MapLineGeometry"];
            properties: components["schemas"]["TransitProperties"];
        };
        /** TransitProperties */
        TransitProperties: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Mode */
            mode?: string | null;
            /** Opening Date */
            opening_date?: string | null;
            /**
             * Tunnel
             * @default false
             */
            tunnel: boolean;
            /**
             * Bridge
             * @default false
             */
            bridge: boolean;
        };
        /** TransitResponse */
        TransitResponse: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Attribution */
            attribution: string;
            /** License */
            license: string;
            /** Copyright Url */
            copyright_url: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Routes */
            routes: components["schemas"]["TransitRoute"][];
            /** Limitations */
            limitations: string[];
            /** Features */
            features: components["schemas"]["TransitFeature"][];
        };
        /** TransitRoute */
        TransitRoute: {
            /** Osm Id */
            osm_id: number;
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_areas_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Areas"];
                };
            };
        };
    };
    get_area_areas__geo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                geo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Area"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_storefronts_storefronts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storefronts"];
                };
            };
        };
    };
    get_area_history_areas__geo_id__history_get: {
        parameters: {
            query?: {
                metric?: string;
                span?: number | null;
            };
            header?: never;
            path: {
                geo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_area_changes_areas__geo_id__changes_get: {
        parameters: {
            query?: {
                metric?: string;
                from_year?: number;
                to_year?: number;
                span?: number | null;
            };
            header?: never;
            path: {
                geo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_area_businesses_areas__geo_id__businesses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                geo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pois_pois_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessResponse"];
                };
            };
        };
    };
    get_compare_compare_get: {
        parameters: {
            query: {
                geo_ids: string;
                year?: number;
                metrics?: string;
                span?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_places_places_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_overlays_overlays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayResponse"];
                };
            };
        };
    };
    get_transit_transit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitResponse"];
                };
            };
        };
    };
    get_community_catalog_community_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityCatalog"];
                };
            };
        };
    };
    get_layers_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"][];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_segment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
